# GitHub action to build and run test cases when a PR is created for merge to main branch
# This action will run on ubuntu-latest

name: Build and Test
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
            uses: actions/checkout@v2

        - name: Setup JDK 17
            uses: actions/setup-java@v2
            with:
                java-version: '17'
                distribution: 'temurin'

        - name: Build with Maven
            run: mvn -B package -DskipTests --file pom.xml

        - name: Run tests with Maven
            run: mvn -B test -Dmaven.test.failure.ignore=true --file pom.xml

        - name: Upload test results
            uses: dorny/action-upload-test-results@v2
            with:
                files: |
                    target/surefire-reports/TEST-*.xml
                github_token: ${{ secrets.GITHUB_TOKEN }}
                check_name: Test Results
                name: Test Results
                working_directory: target/surefire-reports
                fail_on_failure: true

    ```